const translations = {
  vietnamese: {
    "dashboard": "Thống kê",
    "view-site": "Xem trang báo",
    "notifications": "Thông báo",
    "user-management": "Quản lý người dùng",
    "post-management": "Quản lý bài viết",
    "comment-management": "Quản lý bình luận",
    "category-management": "Quản lý danh mục",
    "activity": "Hoạt động",
    "settings": "Cài đặt",
    "logout": "Đăng xuất",
    "good-morning": "Chào buổi sáng",
    "good-morning-msg": "Chúc bạn một ngày làm việc hiệu quả!",
    "font-size": "Cỡ Chữ",
    "language": "Ngôn Ngữ",
    "greet-morning": "Chào buổi sáng",
    "greet-morning-msg": "Chúc bạn một ngày làm việc hiệu quả!",
    "greet-noon": "Chào buổi trưa",
    "greet-noon-msg": "Ăn trưa vui vẻ nha!",
    "greet-afternoon": "Chào buổi chiều",
    "greet-afternoon-msg": "Chiều năng suất nha!",
    "greet-evening": "Chào buổi tối",
    "greet-evening-msg": "Tối rồi, nghỉ ngơi một chút nhé!",
    "greet-night": "Chúc ngủ ngon",
    "greet-night-msg": "Nhớ ngủ sớm để giữ sức khỏe 💤",
    "table-id": "ID",
    "table-title": "Tiêu đề",
    "table-content": "Nội dung",
    "table-date": "Ngày nhận",
    "table-status": "Trạng thái",
    "table-action": "Hành động",
    "settings-general": "Cài Đặt Chung",
    "settings-appearance": "Giao Diện",
    "site-name": "Tên Website",
    "site-description": "Mô tả Website",
    "timezone": "Múi Giờ",
    "maintenance-mode": "Chế Độ Bảo Trì",
    "dark-mode": "Chế Độ Tối",
    "save-settings": "Lưu Cài Đặt",
    "total-posts": ["Tổng bài viết", "Số bài viết"],
    "user": "Người dùng",
    "users": "Tổng người dùng",
    "categories": "Danh mục",
    "comments": "Bình luận",
    "recent-activities": "Hoạt động gần đây",
    "view-articles": "Xem trang báo",
    "username": ["Tên người dùng", "Người bình luận"],
    "roles": "Vai trò",
    "sign-in": "Ngày đăng ký",
    "author": "Tác giả",
    "post-date": "Ngày đăng",
    "add-posts": "Đăng bài viết",
    "add-users": "Thêm người dùng",
    "all": "Tất cả",
    "approved": "Đã duyệt",
    "published": "Đã duyệt",  
    "rejected": "Từ chối",
    "pending": "Chờ duyệt",
    "views": "Lượt xem",
    "filter": "Lọc theo",
    "search": ["Tìm người dùng", "Tìm bài viết", "Tìm bình luận"],
    "admin": "Quản trị viên",
    "banned": "Đã khóa",
    "active": "Hoạt động",
    "topic": "Chủ đề",
    "description": "Mô tả",
    "parent": "Danh mục cha",
    "count" : "Số bài viết",
    "read": "Đã đọc",
    "unread": "Chưa đọc",
    "categories-list": {
      "Âm nhạc": "Âm nhạc",
      "Châu Á": "Châu Á",
      "US-UK": "US-UK",
      "Việt Nam": "Việt Nam",
      "Beauty & Fashion": "Beauty & Fashion",
      "Làm đẹp": "Làm đẹp",
      "Phong cách": "Phong cách",
      "Thời trang": "Thời trang",
      "Trending": "Trending",
      "Đời sống": "Đời sống",
      "Soi sao": "Soi sao",
      "Sống xanh": "Sống xanh",
      "Phim ảnh": "Phim ảnh",
      "Phim chiếu rạp": "Phim chiếu rạp",
      "Phim quốc tế": "Phim quốc tế",
      "Phim truyền hình": "Phim truyền hình",
      "Phim Việt Nam": "Phim Việt Nam",
      "Sức khỏe": "Sức khỏe",
      "Các bệnh": "Các bệnh",
      "Dinh dưỡng": "Dinh dưỡng",
      "Giới tính": "Gender",
      "Khỏe đẹp": "Wellness",
      "Xã hội": "Society",
      "Điểm nóng": "Hot Topics",
      "Pháp luật": "Law",
      "Thế giới đó đây": "Around the World",
   },
   "title.admin_page": "Trang Quản Trị",
      "spam": "Spam",
      "cancel": "Huỷ",
      "save": "Lưu",
      "edit": "Chỉnh sửa",
      "confirm": "Xác nhận",
      "confirm-action": "Xác nhận hành động",
      "lock": "khóa",
      "unlock": "mở khóa",
      "confirm-message": "Bạn có chắc muốn {{action}} người dùng này?",
      "no-parent": "Không có",
      "view-more": "Xem Thêm",
      "today": "Hôm Nay",
      "week": "Tuần Này",
      "month": "Tháng Này",
      "timezone-vietnam": "(GMT+7) Giờ Việt Nam",
      "timezone-gmt": "(GMT+0) Giờ GMT",
      "timezone-est": "(GMT-5) Giờ EST",
      "font-small": "Nhỏ",
      "font-medium": "Vừa",
      "font-large": "Lớn",
      "lang-vietnamese": "Tiếng Việt",
      "lang-english": "Tiếng Anh",
      "views-high-low": "Cao - Thấp",
      "views-low-high": "Thấp - Cao",
      "fullname": "Họ tên",
      "phone": "Điện thoại",
      "experience": "Kinh nghiệm",
      "portfolio": "Portfolio",
      "front-id": "Ảnh thẻ nhà báo mặt trước",
      "back-id": "Ảnh thẻ nhà báo mặt sau",
      "approve": "Duyệt đơn",
      "reject": "Từ chối",
      "email": "Email",
      "password": "Mật khẩu",
      "posts": "Bài Viết",
      "slug": "Slug",
      "author-requests": "Quản lý đơn đăng ký tác giả",
      "add-category-button": "Thêm danh mục",
      "add-category-subtitle": "Thêm danh mục mới",
      "confirm-approve-post": "Bạn có chắc muốn duyệt bài viết này?",
      "confirm-reject-post": "Bạn muốn từ chối bài viết này?",
      "confirm-unapprove-post": "Bạn muốn gỡ duyệt bài viết này?",
      "confirm-delete-post": "Bạn có chắc muốn xóa bài viết này?",

      "noti-approve-title": "Bài viết đã được duyệt",
      "noti-approve-msg": "Chúc mừng bạn, bài viết {{title}} đã được duyệt",

      "noti-reject-title": "Bài viết đã bị từ chối",
      "noti-reject-msg": "Bài viết {{title}} đã không được phê duyệt",

      "noti-unapprove-title": "Bài viết đang được xem xét lại",
      "noti-unapprove-msg": "Bài viết {{title}} đang được duyệt lại",

      "noti-delete-title": "Bài viết đã bị xoá",
      "noti-delete-msg": "Bài viết {{title}} đã bị xoá",
      "chart-users-title": "Người dùng mới theo tháng",
      "chart-users-label": "Người dùng mới",
      "chart-posts-title": "Bài viết theo tháng",
      "chart-posts-label": "Bài viết",
      "month-1": "Tháng 1",
      "month-2": "Tháng 2",
      "month-3": "Tháng 3",
      "month-4": "Tháng 4",
      "month-5": "Tháng 5",
      "month-6": "Tháng 6",
      "month-7": "Tháng 7",
      "month-8": "Tháng 8",
      "month-9": "Tháng 9",
      "month-10": "Tháng 10",
      "month-11": "Tháng 11",
      "month-12": "Tháng 12"
  },
  english: {
    "dashboard": "Dashboard",
    "view-site": "View Site",
    "notifications": "Notifications",
    "user-management": "User Management",
    "post-management": "Post Management",
    "comment-management": "Comment Management",
    "category-management": "Category Management",
    "activity": "Activity",
    "settings": "Settings",
    "logout": "Logout",
    "good-morning": "Good morning",
    "good-morning-msg": "Wishing you a productive day!",
    "font-size": "Font Size",
    "language": "Language",
    "greet-morning": "Good morning",
    "greet-morning-msg": "Wishing you a productive day!",
    "greet-noon": "Good noon",
    "greet-noon-msg": "Enjoy your lunch!",
    "greet-afternoon": "Good afternoon",
    "greet-afternoon-msg": "Stay productive this afternoon!",
    "greet-evening": "Good evening",
    "greet-evening-msg": "Take a rest, it's evening!",
    "greet-night": "Good night",
    "greet-night-msg": "Sleep early and stay healthy 💤",
    "table-id": "ID",
    "table-title": "Title",
    "table-content": "Content",
    "table-date": "Received Date",
    "table-status": "Status",
    "table-action": "Action",
    "settings-general": "General Settings",
    "settings-appearance": "Appearance",
    "site-name": "Website Name",
    "site-description": "Website Description",
    "timezone": "Timezone",
    "maintenance-mode": "Maintenance Mode",
    "dark-mode": "Dark Mode",
    "save-settings": "Save Settings",
    "categories": "Categories",
    "user": "User",
    "users": "Users",
    "comments": "Comments",
    "total-posts": ["Total Posts", "Total Posts"],
    "author": "Author",
    "roles": "Role",
    "views": "Views",
    "post-date": "Posted Date",
    "topic": "Topic",
    "search": ["Search user", "Search post", "Search comment"],
    "add-posts": "Add Post",
    "add-users": "Add User",
    "approved": "Approved",
    "published": "Published",
    "rejected": "Rejected",
    "pending": "Pending",
    "sign-in": "Signup Date",
    "active": "Active",
    "admin": "Administrator",
    "banned": "Banned",
    "all": "All",
    "filter": "Filter",
    "recent-activities": "Recent Activities",
    "view-articles": "View Articles",
    "username": ["Username", "Commenter"],
    "description": "Description",
    "parent": "Parent-id",
    "categories-list": {
      "Âm nhạc": "Music",
      "Châu Á": "Asia",
      "US-UK": "US-UK",
      "Việt Nam": "Vietnam",
      "Beauty & Fashion": "Beauty & Fashion",
      "Làm đẹp": "Beauty",
      "Phong cách": "Style",
      "Thời trang": "Fashion",
      "Trending": "Trending",
      "Đời sống": "Lifestyle",
      "Soi sao": "Celebrities",
      "Sống xanh": "Green Living",
      "Phim ảnh": "Movies",
      "Phim chiếu rạp": "Cinemas",
      "Phim quốc tế": "International Movies",
      "Phim truyền hình": "TV Shows",
      "Phim Việt Nam": "Vietnamese Movies",
      "Sức khỏe": "Health",
      "Các bệnh": "Diseases",
      "Dinh dưỡng": "Nutrition",
      "Giới tính": "Gender",
      "Khỏe đẹp": "Wellness",
      "Xã hội": "Society",
      "Điểm nóng": "Hot Topics",
      "Pháp luật": "Law",
      "Thế giới đó đây": "Around the World"
    },
    "title.admin_page": "Admin Dashboard",
    "spam": "Spam",
    "cancel": "Cancel",
    "save": "Save",
    "edit": "Edit",
    "confirm": "Confirm",
    "confirm-action": "Confirm Action",
    "confirm-message": "Are you sure you want to {{action}} this user?",
    "lock": "lock",
    "unlock": "unlock",
    "no-parent": "None",
    "view-more": "View More",
    "today": "Today",
    "week": "This Week",
    "month": "This Month",
    "timezone-vietnam": "(GMT+7) Vietnam Time",
    "timezone-gmt": "(GMT+0) GMT",
    "timezone-est": "(GMT-5) EST",
    "font-small": "Small",
    "font-medium": "Medium",
    "font-large": "Large",
    "lang-vietnamese": "Vietnamese",
    "lang-english": "English",
    "views-high-low": "High - Low",
    "views-low-high": "Low - High",
    "fullname": "Full Name",
    "phone": "Phone",
    "experience": "Experience",
    "portfolio": "Portfolio",
    "front-id": "Press ID Front",
    "back-id": "Press ID Back",
    "approve": "Approve Request",
    "reject": "Reject",
    "email": "Email",
    "password": "Password",
    "posts": "Posts",
    "slug": "Slug",
    "author-requests": "Manage Author Requests",
    "read": "Read",
    "unread": "Unread",
    "add-category-button": "Add category",
    "add-category-subtitle": "Add new category",
    "confirm-approve-post": "Are you sure you want to approve this post?",
    "confirm-reject-post": "Do you want to reject this post?",
    "confirm-unapprove-post": "Do you want to unapprove this post?",
    "confirm-delete-post": "Are you sure you want to delete this post?",

    "noti-approve-title": "Your post has been approved",
    "noti-approve-msg": "Congratulations, your post {{title}} has been approved.",

    "noti-reject-title": "Your post has been rejected",
    "noti-reject-msg": "We're sorry to inform you that your post {{title}} has not been approved.",

    "noti-unapprove-title": "Your post is under review again",
    "noti-unapprove-msg": "Your post {{title}} is being re-evaluated.",

    "noti-delete-title": "Your post has been deleted",
    "noti-delete-msg": "Your post {{title}} has been removed.",
    "chart-users-title": "New Users by Month",
    "chart-users-label": "New Users",
    "chart-posts-title": "Posts by Month",
    "chart-posts-label": "Posts",
    "month-1": "January",
    "month-2": "February",
    "month-3": "March",
    "month-4": "April",
    "month-5": "May",
    "month-6": "June",
    "month-7": "July",
    "month-8": "August",
    "month-9": "September",
    "month-10": "October",
    "month-11": "November",
    "month-12": "December"
  }
};


